# Generated by Django 3.2 on 2021-07-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditormodel',
            name='name',
            field=models.CharField(blank=True, help_text='People who iSpace work', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='journalmodel',
            name='dr_account',
            field=models.CharField(blank=True, choices=[('Office Expense', 'Office Expense'), ('Statutory obligation', 'Statutory obligation'), ('Office Expense', 'Office Expense'), ('Office Expense', 'Office Expense'), ('Office Expense', 'Office Expense')], help_text='Where is the money going', max_length=120),
        ),
    ]
