# Generated by Django 3.2 on 2021-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210708_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='finance/pettycash/'),
        ),
    ]
