# Generated by Django 3.2 on 2021-07-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210708_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyProjections',
            new_name='WeeklyProjection',
        ),
    ]
