# Generated by Django 3.2 on 2021-07-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_journalmodel_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalmodel',
            name='cr_account',
            field=models.CharField(blank=True, choices=[('Revenue', 'Revenue'), ('Momo', 'Momo'), ('Bank', 'Bank'), ('Cash at Hand', 'Cash at Hand')], help_text='Where is the money leaving', max_length=120),
        ),
        migrations.AlterField(
            model_name='journalmodel',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='finance/journal'),
        ),
        migrations.AlterField(
            model_name='journalmodel',
            name='dr_account',
            field=models.CharField(blank=True, choices=[('Momo', 'Momo'), ('Bank', 'Bank'), ('Cash at Hand', 'Cash at Hand'), ('Office Expense', 'Office Expense'), ('Statutory obligation', 'Statutory obligation'), ('Office Expense', 'Office Expense'), ('Office Expense', 'Office Expense'), ('Office Expense', 'Office Expense')], help_text='Where is the money going', max_length=120),
        ),
    ]
