# Generated by Django 3.2 on 2021-07-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacesmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='spacesmodel',
            name='space_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spacesmodel',
            name='space_img',
            field=models.ImageField(blank=True, upload_to='spaces/'),
        ),
    ]
