# Generated by Django 3.2 on 2021-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeadmin', '0003_rename_space_slug_spacesmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacesmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
