# Generated by Django 3.2 on 2021-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeadmin', '0004_alter_spacesmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spaceusersmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmembersmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
