# Generated by Django 3.2 on 2021-07-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeadmin', '0006_spaceusersmodel_space_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spaceusersmodel',
            old_name='companyname',
            new_name='name',
        ),
    ]
