# Generated by Django 3.2 on 2021-07-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeadmin', '0008_auto_20210706_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacesmodel',
            name='is_bookable',
            field=models.BooleanField(default=False, help_text='Only Tick is a space is bookable like event / meeting '),
        ),
    ]
