# Generated by Django 3.2 on 2021-07-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeadmin', '0009_spacesmodel_is_bookable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='officedocs/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officeadmin.studentsmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SpaceUserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('spaceuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officeadmin.spaceusersmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
